### ISSUE TITLE
Error when creating a game with 3 automa

### ISSUE THREAD

**Issue by RyanelRichie** [brdgm/gaia-project-solo-helper#4]
Any time I try to start a game with 3 automatic I get the error attached. Have tried three different browsers and multiple factions. 
<img width="666" alt="Screenshot 2024-06-26 at 10 20 21 AM" src="https://github.com/brdgm/gaia-project-solo-helper/assets/165414704/42ee6311-49ee-4b89-bc61-d6bed73878d0">

**Comment by stefanseifert** [comment]
good catch! - please try again with v1.0.2, available in a few minutes

**Comment by RyanelRichie** [comment]
Works!! Thanks so much for the quick response. This is going to help the game hit my table so much more.
